; GrowAI - ESP32 principal (DevKit 30 pinos)
; Compilar: pio run -d firmware/esp32-main
; Gravar:   pio run -d firmware/esp32-main -t upload
; Serial:   pio device monitor -b 115200

[env:esp32dev]
platform  = espressif32@6.9.0     ; Arduino core 2.0.17 - versao fixa de proposito
board     = esp32dev
framework = arduino

monitor_speed = 115200
monitor_filters = esp32_exception_decoder

build_flags =
    -I ../shared
    -Wall

lib_deps =
    bblanchon/ArduinoJson@^7.0.0
    tzapu/WiFiManager@^2.0.17
    paulstoffregen/OneWire@^2.3.7
    milesburton/DallasTemperature@^3.11.0
